"""adds exchange rate table

Revision ID: 78c353648ee5
Revises: c4a60cce5b6f
Create Date: 2025-05-28 21:27:35.088634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c353648ee5'
down_revision: Union[str, None] = 'c4a60cce5b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbo1', sa.String(), nullable=True))
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('symbo1')

    # ### end Alembic commands ###
