"""adds symbol column

Revision ID: b51eb6127efa
Revises: 78c353648ee5
Create Date: 2025-05-28 21:53:18.679916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51eb6127efa'
down_revision: Union[str, None] = '78c353648ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(), nullable=True))
        batch_op.drop_column('symbo1')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbo1', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
